[2024-07-11T14:51:17.647+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T14:51:17.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_V1.greet manual__2024-07-11T14:51:16.885755+00:00 [queued]>
[2024-07-11T14:51:17.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_V1.greet manual__2024-07-11T14:51:16.885755+00:00 [queued]>
[2024-07-11T14:51:17.693+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-11T14:51:17.748+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): greet> on 2024-07-11 14:51:16.885755+00:00
[2024-07-11T14:51:17.755+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'python_dag_V1', 'greet', 'manual__2024-07-11T14:51:16.885755+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/python_dag.py', '--cfg-path', '/tmp/tmp8jdoc6wl']
[2024-07-11T14:51:17.757+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask greet
[2024-07-11T14:51:17.759+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1242) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-11T14:51:17.761+0000] {standard_task_runner.py:63} INFO - Started process 1244 to run task
[2024-07-11T14:51:17.908+0000] {task_command.py:426} INFO - Running <TaskInstance: python_dag_V1.greet manual__2024-07-11T14:51:16.885755+00:00 [running]> on host 54a03ee1424c
[2024-07-11T14:51:18.105+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayzo' AIRFLOW_CTX_DAG_ID='python_dag_V1' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T14:51:16.885755+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T14:51:16.885755+00:00'
[2024-07-11T14:51:18.106+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T14:51:18.122+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T14:51:18.123+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/python_dag.py", line 12, in greet
    ti=ti.xcoms_pull(task_ids='get_name')
       ^^^^^^^^^^^^^
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'. Did you mean: 'xcom_pull'?
[2024-07-11T14:51:18.141+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=python_dag_V1, task_id=greet, run_id=manual__2024-07-11T14:51:16.885755+00:00, execution_date=20240711T145116, start_date=20240711T145117, end_date=20240711T145118
[2024-07-11T14:51:18.222+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 1244)
[2024-07-11T14:51:18.259+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T14:51:18.276+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T14:51:18.376+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
