[2024-07-15T16:17:12.192+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: Postgres_dag.insert_into_table manual__2024-07-15T16:14:36.136595+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
